export enum URLS {
  "LOGIN" = "/new/login/",
  "WELCOME" = "/new/welcome/",
  "PASSWORDRESET" = "/new/password-reset/",
  "CREATEACCOUNT" = "/new/create-account/",
  "DASHBOARD" = "/new/dashboard/",
  "LEAGUE" = "/new/league/",
  "LEAGUEADMIN" = "/new/manage-league/",
  "CREATELEAGUE" = "/new/create-league/",
  "EDITPROFILE" = "/new/edit-profile/",
  "PLAYLEAGUE" = "/new/play-league/",
  "RESULTSLEAGUE" = "/new/results-league/",
  "STATSLEAGUE" = "/new/stats-league/",
  "RULES" = "/new/rules/",
  "PLAYDOGFIGHT" = "/new/play-dogfight/",
  "RESULTSDOGFIGHT" = "/new/results-dogfight/",
  "STATSDOGFIGHT" = "/new/stats-dogfight/",
}
